name: Docker Image CI/CD
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        run: docker build -t ${{ secrets.DOCKER_REGISTRY }}:latest ./
      - name: Login to registry
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASS }} registry.cn-hangzhou.aliyuncs.com
      - name: Push Image
        run: docker push ${{ secrets.DOCKER_IMAGE_NAME }}:latest
  pull-docker:
    needs: [build]
    name: Pull Docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASS }}
          port: ${{ secrets.HOST_PORT }}
          script: |
            docker ps -q --filter "name=${{ secrets.DOCKER_IMAGE_NAME }}" | grep -q . && docker stop ${{ secrets.DOCKER_IMAGE_NAME }} && docker rm -fv ${{ secrets.DOCKER_IMAGE_NAME }} && docker rmi ${{ secrets.DOCKER_IMAGE_NAME }}:latest
            docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASS }} registry.cn-hangzhou.aliyuncs.com
            docker pull ${{ secrets.DOCKER_IMAGE_NAME }}:latest
            docker run --name ${{ secrets.DOCKER_IMAGE_NAME }}  -d -p 80:80 ${{ secrets.DOCKER_REGISTRY }}:latest
